// The repo read — DESIGN §4's tests-as-code store, read side only (PLAN Phase
// 4). The contract, and the reasoning behind it, live in `./types.js`; this
// file is its implementation and adds no rules of its own.
//
// Four properties are worth more than the code that produces them.
//
// First, every way this reader can fail to see the whole picture leaves a
// mark. A manifest that exists and could not be turned into an inventory
// throws (see `SpecStoreFaultError` — an empty inventory is a CLAIM, and the
// most dangerous wrong one this package can make); anything narrower — a
// rotten entry, a registered file that is gone, a directory that would not
// list — is a `warning` note. Two paths reach an empty answer without a
// warning — no manifest at all, and a manifest that registers nothing — and
// each says which of the two it is in an `info` note by name.
//
// Second, one bad entry must not blind the reader to the other forty. A
// manifest is hand-edited and machine-generated by turns, so a single entry
// with a numeric `kind` is an ordinary occurrence rather than a catastrophe:
// it is dropped, named in a warning, and the rest of the file is read.
//
// Third, every field arrives as wire data and is validated rather than cast.
// The manifest is repo data reviewed by a human (see the TM-1 note in
// `./types.js`), which is an argument about TRUST, not about SHAPE — a typo
// survives review effortlessly, and `entry.targets[0].sysId` on a hand-edited
// file is a crash inside somebody else's stage.
//
// Fourth, nothing here opens a spec file. Existence is checked, the body is
// not read: the inventory joins on identity and declared targets (QA-16), and
// reading the spec body needs the YAML step schema that belongs to the
// projection writer.

import { open, readdir, realpath, stat } from "node:fs/promises";
import path from "node:path";

import { TEST_KINDS } from "@tessera/types";
import type { TargetArtifactRef, TestKind, TestSpec } from "@tessera/types";

import { SpecInputError, SpecStoreFaultError } from "./errors.js";
import {
  PROPOSED_SPECS_DIRNAME,
  SPEC_MANIFEST_FILENAME,
  SPEC_MANIFEST_MAX_BYTES,
  SPEC_MANIFEST_VERSION,
} from "./types.js";
import type {
  InventoryNote,
  InventoryNoteLevel,
  ReadInventoryOptions,
  SpecInventory,
} from "./types.js";

/**
 * What a spec file looks like in the DESIGN §4 layout — `<Name>.unit.ts`,
 * `<Name>.e2e.atf.yaml`, `<flow>.spec.ts`.
 *
 * This is a heuristic and is used for ONE thing: noticing files the manifest
 * does not mention, so the report can say the repo may intend more than it
 * lists. It is never a join and never produces a spec — QA-16 forbids reading
 * a target out of a path, and a file matched here has no declared targets at
 * all, so there is nothing honest to join it to.
 */
export const SPEC_FILE_SUFFIXES = [
  ".unit.ts",
  ".e2e.atf.yaml",
  ".e2e.atf.yml",
  ".spec.ts",
] as const;

/**
 * The suffixes a REGISTERED spec of each kind must carry — the same partition
 * `@tessera/generate` enforces on what it writes (`ALLOWED_SUFFIXES` in its
 * writer.ts, which cannot import from here without a cycle of intent).
 *
 * Delegated decision 2026-09-26 (review L4): the manifest used to accept any
 * path under any kind, so `.manifest.json` registered as a `unit` spec read
 * back as a complete inventory. An entry whose path does not end in one of its
 * kind's suffixes — exact case, as the sweep matches — is now dropped with a
 * warning. Fail closed: a runner picks its executor by kind, and a file named
 * for another kind (or for none) is one it would either misrun or never run.
 */
export const KIND_SPEC_SUFFIXES: Readonly<
  Record<TestKind, readonly (typeof SPEC_FILE_SUFFIXES)[number][]>
> = {
  unit: [".unit.ts"],
  e2e: [".e2e.atf.yaml", ".e2e.atf.yml"],
  ui: [".spec.ts"],
};

/**
 * A long list in one note is a line nobody reads to the end. The tail keeps the
 * count truthful once the head has stopped being useful.
 */
const UNREGISTERED_LIST_CAP = 10;

function note(level: InventoryNoteLevel, message: string): InventoryNote {
  return { level, message };
}

/**
 * Deterministic, locale-independent string order — the same reason
 * `@tessera/impact` refuses `localeCompare`: a CI log that sorts differently on
 * two runners is a log nobody can diff.
 */
function compare(left: string, right: string): number {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * `Array.isArray` widens an `unknown` to `any[]`, which would hand every
 * element out untyped — the one thing this file must not do with wire data.
 */
function isArray(value: unknown): value is readonly unknown[] {
  return Array.isArray(value);
}

/** Blank is not a value: `id: " "` names nothing and joins to nothing. */
function isNonBlank(value: unknown): value is string {
  return typeof value === "string" && value.trim() !== "";
}

function isTestKind(value: unknown): value is TestKind {
  return typeof value === "string" && TEST_KINDS.some((kind) => kind === value);
}

/** Names what was found without printing a caller-supplied object wholesale. */
function shapeOf(value: unknown): string {
  if (value === undefined) return "absent";
  if (value === null) return "null";
  if (isArray(value)) return "an array";
  if (typeof value === "string") {
    return value.trim() === "" ? "blank" : `the string "${value}"`;
  }
  return `a ${typeof value}`;
}

function describeError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** The errno of a failed fs call, when the runtime supplied one. */
function errnoOf(error: unknown): string | undefined {
  if (typeof error !== "object" || error === null || !("code" in error)) {
    return undefined;
  }
  return typeof error.code === "string" ? error.code : undefined;
}

function relativeName(root: string, target: string): string {
  const relative = path.relative(root, target);
  return relative === "" ? "." : relative;
}

/**
 * Containment by path segments rather than by string prefix: `startsWith` says
 * `/tests-old/x` is inside `/tests`, and a leading-`..` test alone rejects a
 * legitimately named `..config.unit.ts`.
 */
function isInside(root: string, candidate: string): boolean {
  const relative = path.relative(root, candidate);
  // Equivalent mutant (POSIX): dropping `path.isAbsolute(relative)` changes
  // nothing off Windows — `path.relative` of two absolute POSIX paths is never
  // absolute. It is kept for win32, where a candidate on another drive is.
  if (relative === "" || path.isAbsolute(relative)) return false;
  return relative.split(path.sep)[0] !== "..";
}

/**
 * The comparison key for "is this the same file": NFC-normalised (APFS
 * compares normalisation-insensitively) and lower-cased. `toLowerCase` is not
 * full Unicode case folding, which only ever makes two keys compare EQUAL
 * less often than a filesystem would — the gap is non-ASCII case pairs.
 */
function foldPath(value: string): string {
  return value.normalize("NFC").toLowerCase();
}

/**
 * The manifest body, refusing anything over `SPEC_MANIFEST_MAX_BYTES`.
 *
 * Delegated decision 2026-09-26 (review L4, INFO): the read was unbounded. The
 * size is checked on the open handle and the read itself stops one byte past
 * the cap, so a file that grows between the two is still caught. Over the cap
 * is a `SpecStoreFaultError`, never a truncated parse or an empty inventory.
 * fs errors (ENOENT, EISDIR, EACCES) propagate unchanged for the caller's
 * existing absent-vs-unreadable split.
 */
async function readManifestCapped(
  manifestPath: string,
  openManifest: (target: string) => Promise<ManifestHandle>,
): Promise<string> {
  const handle = await openManifest(manifestPath);
  try {
    const over = (size: string): SpecStoreFaultError =>
      new SpecStoreFaultError(
        `${manifestPath} is ${size} bytes, which exceeds the ${SPEC_MANIFEST_MAX_BYTES}-byte manifest cap; refusing to read it rather than read part of it`,
      );
    const { size } = await handle.stat();
    if (size > SPEC_MANIFEST_MAX_BYTES) throw over(String(size));
    const buffer = Buffer.alloc(SPEC_MANIFEST_MAX_BYTES + 1);
    let length = 0;
    while (length < buffer.length) {
      // Equivalent mutant: passing `null` as the position (read from the
      // handle's current offset) is indistinguishable — the handle is fresh,
      // starts at 0, and this loop is its only reader, reading contiguously.
      // (The positional test fake in mutation-gaps.test.js does not model a
      // `null` position, so it kills this mutant; a real FileHandle would not.)
      const { bytesRead } = await handle.read(
        buffer,
        length,
        buffer.length - length,
        length,
      );
      if (bytesRead === 0) break;
      length += bytesRead;
    }
    if (length > SPEC_MANIFEST_MAX_BYTES)
      throw over("more than " + String(SPEC_MANIFEST_MAX_BYTES));
    return buffer.toString("utf8", 0, length);
  } finally {
    await handle.close();
  }
}

function isSpecFileName(name: string): boolean {
  return SPEC_FILE_SUFFIXES.some((suffix) => name.endsWith(suffix));
}

/**
 * A validated entry, or the reason it was rejected.
 *
 * `file` survives rejection on purpose. It is what the entry CLAIMED, and the
 * unregistered-files sweep below subtracts claims rather than survivors: a
 * file the manifest names is already reported — by a warning that names it
 * precisely — and listing it a second time as "unregistered" sends the reader
 * hunting for two problems where there is one.
 */
type EntryResult =
  | { readonly ok: true; readonly file: string; readonly spec: TestSpec }
  | {
      readonly ok: false;
      readonly file: string | undefined;
      readonly problem: string;
    };

function rejected(problem: string, file?: string): EntryResult {
  return { ok: false, file, problem };
}

/**
 * One manifest element → one `TestSpec`, or one reason it is not usable.
 *
 * `label` falls back to the array index because the id is the thing being
 * validated: a warning about "the entry with no id" is unactionable in a file
 * with forty of them.
 */
function validateEntry(
  root: string,
  value: unknown,
  index: number,
): EntryResult {
  if (!isRecord(value)) {
    return rejected(`entry #${index} is ${shapeOf(value)}, not an object`);
  }

  const id = value.id;
  const label = isNonBlank(id) ? `\`${id}\`` : `#${index}`;
  if (!isNonBlank(id)) {
    return rejected(`entry ${label} has an \`id\` that is ${shapeOf(id)}`);
  }

  const declaredPath = value.path;
  if (!isNonBlank(declaredPath)) {
    return rejected(
      `entry ${label} has a \`path\` that is ${shapeOf(declaredPath)}`,
    );
  }
  if (path.isAbsolute(declaredPath)) {
    return rejected(
      `entry ${label} has the absolute \`path\` "${declaredPath}"; a spec of this repo is named relative to the tests root`,
    );
  }
  const file = path.resolve(root, declaredPath);
  if (!isInside(root, file)) {
    // Not a security boundary — the manifest is repo data. It is a statement
    // about what the inventory IS: an entry reaching out of the tests tree
    // describes something other than this repo's specs, and joining it would
    // report coverage of a file no reviewer of this repo ever saw.
    return rejected(
      `entry ${label} has the \`path\` "${declaredPath}", which resolves outside the tests root`,
    );
  }

  const kind = value.kind;
  if (!isTestKind(kind)) {
    return rejected(
      `entry ${label} has a \`kind\` that is ${shapeOf(kind)}, expected one of ${TEST_KINDS.join(", ")}`,
      file,
    );
  }
  // See `KIND_SPEC_SUFFIXES` for the delegated decision. `file` is passed so
  // the sweep below does not accuse the same file a second time.
  const suffixes = KIND_SPEC_SUFFIXES[kind];
  if (!suffixes.some((suffix) => declaredPath.endsWith(suffix))) {
    return rejected(
      `entry ${label} has the \`path\` "${declaredPath}", which does not end in the ${kind} spec suffix ${suffixes.join(" or ")}`,
      file,
    );
  }

  const declaredTargets = value.targets;
  if (!isArray(declaredTargets)) {
    return rejected(
      `entry ${label} has \`targets\` that are ${shapeOf(declaredTargets)}, expected an array`,
      file,
    );
  }
  const targets: TargetArtifactRef[] = [];
  for (const [position, target] of declaredTargets.entries()) {
    // The whole entry goes, not the one target. `targets` IS the QA-16
    // declaration, so an entry that keeps three of its four is a spec quietly
    // claiming less than its author wrote — a narrower lie than dropping it.
    if (!isRecord(target)) {
      return rejected(
        `entry ${label} has target #${position} that is ${shapeOf(target)}, not an object`,
        file,
      );
    }
    const table = target.table;
    const sysId = target.sysId;
    const name = target.name;
    if (!isNonBlank(table) || !isNonBlank(sysId) || !isNonBlank(name)) {
      return rejected(
        `entry ${label} has target #${position} without a non-blank table/sysId/name (table is ${shapeOf(table)}, sysId is ${shapeOf(sysId)}, name is ${shapeOf(name)})`,
        file,
      );
    }
    targets.push({ table, sysId, name });
  }

  // An empty `targets` array is valid wire data and is kept: it declares
  // nothing, so it joins to nothing in `computeIntent` and cannot inflate a
  // gap count. It is a spec that has not been pointed at anything yet, which
  // is a review comment rather than a defect in this reader.
  return {
    ok: true,
    file,
    // `path` is the declared string verbatim, not the resolved one. It is what
    // a reviewer greps for and what the diff showed them.
    spec: { ref: { id, path: declaredPath }, kind, targets },
  };
}

interface DiskScan {
  readonly files: readonly string[];
  /** Directories that would not list, rendered for a note. */
  readonly unreadable: readonly string[];
  /** Spec-looking files under `<root>/proposed/` — reported, never counted. */
  readonly proposed: readonly string[];
  /** Directories under `<root>/proposed/` that would not list. */
  readonly proposedUnreadable: readonly string[];
}

/**
 * Every spec-looking file under the root, plus every directory that refused.
 *
 * Symlinks are not followed and dot-entries and `node_modules` are skipped:
 * the first keeps a cycle from turning this into a hang, and the rest are not
 * where DESIGN §4 puts specs.
 */
async function scanSpecFiles(root: string): Promise<DiskScan> {
  const files: string[] = [];
  const unreadable: string[] = [];
  const proposed: string[] = [];
  const proposedUnreadable: string[] = [];
  const proposedDir = path.join(root, PROPOSED_SPECS_DIRNAME);

  const visit = async (
    dir: string,
    found: string[],
    refused: string[],
  ): Promise<void> => {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch (error) {
      refused.push(`${relativeName(root, dir)} (${describeError(error)})`);
      return;
    }
    for (const entry of entries) {
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        // Delegated decision 2026-09-26 (review M2): `<root>/proposed/` is the
        // output directory of `tess generate` — inert, reviewed-before-armed,
        // registered by no live manifest by construction. Sweeping it made the
        // first generated spec turn every inventory incomplete (coverage exit
        // 5, `run --live` INCONCLUSIVE). It is walked into its own bucket and
        // reported as `info`. Exempt ONLY at the tests root and only as a REAL
        // directory (`isDirectory` on a Dirent is false for a symlink, so a
        // link named `proposed` is skipped like every link, and its target is
        // still swept where it really lives); a `proposed/` deeper in the
        // tree is live specs with an unlucky name and is swept as before.
        if (full === proposedDir) {
          await visit(full, proposed, proposedUnreadable);
        } else {
          await visit(full, found, refused);
        }
      } else if (entry.isFile() && isSpecFileName(entry.name)) {
        found.push(full);
      }
    }
  };

  await visit(root, files, unreadable);
  return { files, unreadable, proposed, proposedUnreadable };
}

/** The head of a long list, with the count of the tail it dropped. */
function renderList(items: readonly string[], cap: number): string {
  const head = items.slice(0, cap).join(", ");
  const rest = items.length - cap;
  return rest > 0 ? `${head}, and ${rest} more` : head;
}

/**
 * Deduplicated and ordered by (level, message).
 *
 * Generation order here is already stable, so this is not what makes the run
 * reproducible — it is what keeps it reproducible when a later branch is added
 * in the wrong place, and it puts the `info` summary ahead of the warnings it
 * summarises.
 */
function settleNotes(notes: readonly InventoryNote[]): InventoryNote[] {
  const unique = new Map<string, InventoryNote>();
  // Equivalent mutant: keying on the message alone is indistinguishable, as
  // no message is ever emitted at two levels (every info wording is distinct
  // from every warning wording). The level stays in the key so that remains
  // true by construction rather than by wording.
  for (const item of notes) unique.set(`${item.level} ${item.message}`, item);
  return [...unique.values()].sort(
    (left, right) =>
      compare(left.level, right.level) || compare(left.message, right.message),
  );
}

function inventory(
  specs: readonly TestSpec[],
  notes: readonly InventoryNote[],
): SpecInventory {
  const settled = settleNotes(notes);
  return {
    specs,
    notes: settled,
    // Computed, never hand-set per branch: `SpecInventory` defines `incomplete`
    // as "some note is a warning", and a branch that pushes a warning while
    // forgetting the flag is precisely the silent short list this package
    // exists to prevent.
    incomplete: settled.some((item) => item.level === "warning"),
  };
}

/**
 * Test seams for `readSpecInventoryWithSeams`. NOT re-exported from
 * `index.ts`, and the package `exports` map names `index.js` only, so no
 * consumer can reach it — the tests import `build/inventory.js` by path.
 *
 * Delegated decision 2026-09-30 (wave 14): the one-file-two-ids dedupe keys on
 * a case-folded, NFC-normalised real path AND lexical path. On APFS `realpath`
 * already canonicalises case and normalisation, so on the macOS dev machine
 * the fold and the lexical key were unobservable and three-plus mutants of
 * them survived. Injecting `realpath` lets a test play a filesystem that does
 * not canonicalise (ext4) or that resolves a case alias elsewhere, on every
 * OS. `openManifest` exists for the same reason on the capped read: the
 * post-read cap check and the loop bound are reached only by a source whose
 * `stat` under-reports (a file growing after `stat`, a device, a pipe), which
 * a test cannot stage deterministically on a real filesystem. Additive and
 * reversible: the production path passes no seams and calls
 * `node:fs/promises` `realpath` and `open(path, "r")`, exactly as before.
 */
export interface InventorySeams {
  readonly realpath?: (target: string) => Promise<string>;
  readonly openManifest?: (target: string) => Promise<ManifestHandle>;
}

/** The slice of `FileHandle` the capped manifest read uses. */
export interface ManifestHandle {
  stat(): Promise<{ readonly size: number }>;
  read(
    buffer: Buffer,
    offset: number,
    length: number,
    position: number,
  ): Promise<{ readonly bytesRead: number }>;
  close(): Promise<void>;
}

/**
 * What the repo says it intends to test, read from `<root>/.manifest.json`
 * and the tree beneath it.
 *
 * Throws `SpecInputError` when `root` is not a usable tests root, and
 * `SpecStoreFaultError` when the manifest is there but unusable. Everything
 * else that goes wrong comes back as a `warning` note with `incomplete` set —
 * see `SpecInventory` for why the two are not interchangeable.
 */
export async function readSpecInventory(
  options: ReadInventoryOptions,
): Promise<SpecInventory> {
  return readSpecInventoryWithSeams(options, {});
}

/** `readSpecInventory` with its filesystem resolution injectable (tests only). */
export async function readSpecInventoryWithSeams(
  options: ReadInventoryOptions,
  seams: InventorySeams,
): Promise<SpecInventory> {
  const resolveReal = seams.realpath ?? realpath;
  const openManifest =
    seams.openManifest ?? ((target: string) => open(target, "r"));
  // ── 1. the root ─────────────────────────────────────────────────────────
  // A blank root resolves to the process cwd, which is an accident every time
  // and a request never — catching it here keeps the walk below off a tree
  // nobody named.
  if (!isNonBlank(options.root)) {
    throw new SpecInputError(
      `the tests root is ${shapeOf(options.root)}; name the directory holding ${SPEC_MANIFEST_FILENAME} (DESIGN §4)`,
    );
  }
  const root = path.resolve(options.root);

  let rootStat;
  try {
    rootStat = await stat(root);
  } catch (error) {
    // Includes ENOENT and EACCES alike: both mean this path cannot be used as
    // a tests root, and the fix for both is a different argument.
    throw new SpecInputError(
      `the tests root ${root} is not readable as a directory: ${describeError(error)}`,
      { cause: error },
    );
  }
  if (!rootStat.isDirectory()) {
    throw new SpecInputError(`the tests root ${root} is not a directory`);
  }
  // The root's REAL path, for the per-entry containment check below. The
  // root may legitimately sit behind a link (`/var` → `/private/var` on
  // macOS), so a resolved entry is compared with a resolved root.
  let realRoot: string;
  try {
    realRoot = await resolveReal(root);
  } catch (error) {
    throw new SpecInputError(
      `the tests root ${root} could not be resolved: ${describeError(error)}`,
      { cause: error },
    );
  }

  // ── 2. the manifest ─────────────────────────────────────────────────────
  const manifestPath = path.join(root, SPEC_MANIFEST_FILENAME);
  let raw: string;
  try {
    raw = await readManifestCapped(manifestPath, openManifest);
  } catch (error) {
    if (error instanceof SpecStoreFaultError) throw error;
    if (errnoOf(error) !== "ENOENT") {
      // The OPP-1b trap with a different errno: a registry that is there and
      // will not open says nothing about what the repo intends, and must not
      // collapse into a registry that says nothing is intended.
      throw new SpecStoreFaultError(
        `${manifestPath} exists but could not be read: ${describeError(error)}`,
        { cause: error },
      );
    }
    // The one honest empty answer. A tests root with no registry yet is a real
    // repo state — someone ran `mkdir tests` — and the note names that case
    // explicitly so it can never be mistaken in a log for a read that failed.
    //
    // It says nothing about the tree, because nothing here looked at it: the
    // scan below runs only on the branch that has a manifest to compare it
    // against. "Nothing is registered" is what was observed; "the repo intends
    // nothing" would be a claim about files this branch never opened a
    // directory to see.
    return inventory(
      [],
      [
        note(
          "info",
          `no ${SPEC_MANIFEST_FILENAME} in ${root}: the tests root exists and registers no specs yet, so this inventory is empty because nothing is registered — not because anything could not be read. The tree under the root was not scanned, so this says nothing about whether spec-looking files are already sitting there unregistered`,
        ),
      ],
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new SpecStoreFaultError(
      `${manifestPath} is not valid JSON: ${describeError(error)}`,
      { cause: error },
    );
  }
  if (!isRecord(parsed)) {
    throw new SpecStoreFaultError(
      `${manifestPath} is ${shapeOf(parsed)}, expected a manifest object with \`version\` and \`specs\``,
    );
  }

  const version = parsed.version;
  if (typeof version !== "number") {
    throw new SpecStoreFaultError(
      `${manifestPath} has a \`version\` that is ${shapeOf(version)}, expected the number ${SPEC_MANIFEST_VERSION}`,
    );
  }
  if (version !== SPEC_MANIFEST_VERSION) {
    // Reading a newer manifest on a guess is how a reader silently drops the
    // fields it does not know about — including, one day, a field that says
    // which specs are disabled.
    throw new SpecStoreFaultError(
      `${manifestPath} is version ${version}; this reader understands version ${SPEC_MANIFEST_VERSION} only, and reading it anyway would silently drop whatever the newer format added`,
    );
  }

  const declaredSpecs = parsed.specs;
  if (!isArray(declaredSpecs)) {
    throw new SpecStoreFaultError(
      `${manifestPath} has \`specs\` that are ${shapeOf(declaredSpecs)}, expected an array`,
    );
  }

  // ── 3. the entries ──────────────────────────────────────────────────────
  const notes: InventoryNote[] = [];
  const specs: TestSpec[] = [];
  const byId = new Map<string, TestSpec>();
  const claimed = new Set<string>();
  // Case-folded real path AND case-folded lexical path → the id that took it.
  const byFile = new Map<string, string>();

  for (const [index, value] of declaredSpecs.entries()) {
    const result = validateEntry(root, value, index);
    // Equivalent mutant: adding `undefined` unconditionally is invisible —
    // `claimed` is only ever probed with the string paths the scan found.
    if (result.file !== undefined) claimed.add(result.file);
    if (!result.ok) {
      notes.push(note("warning", `dropped ${result.problem}`));
      continue;
    }

    const { spec, file } = result;
    if (byId.has(spec.ref.id)) {
      // First wins, and the loser is named. Identity that is not unique is not
      // identity: silently keeping the last would make the inventory depend on
      // the order two people happened to merge their manifest edits in.
      notes.push(
        note(
          "warning",
          `dropped entry \`${spec.ref.id}\` at "${spec.ref.path}": a spec with this id is already registered earlier in the manifest, and the first one was kept`,
        ),
      );
      continue;
    }

    // Sequential rather than fanned out with `Promise.all`. Nothing about the
    // result requires it — the notes are sorted on the way out — but a serial
    // walk keeps the number of open file handles proportional to nothing at
    // all, and a manifest is tens of entries, not thousands.
    let dropped: string | undefined;
    let fileKeys: readonly string[] = [];
    try {
      const fileStat = await stat(file);
      // Equivalent mutant: resolving unconditionally is indistinguishable on a
      // real filesystem — `stat` just succeeded on this path, and `realpath`
      // needs no more than `stat` did (search permission on each component),
      // so the non-file branch below is reached with the same message either
      // way. The guard only saves a syscall.
      const realFile = fileStat.isFile() ? await resolveReal(file) : "";
      if (!fileStat.isFile()) {
        dropped = `"${spec.ref.path}" exists but is not a regular file`;
      } else if (!isInside(realRoot, realFile)) {
        // Delegated decision 2026-09-25: `validateEntry`'s containment check
        // is lexical, and `stat` follows links — so `a.unit.ts ->
        // ../outside.unit.ts` passed both and was registered as a spec of
        // this repo. The rule is judged again on the fully resolved path and
        // the entry is DROPPED with a warning (which sets `incomplete`),
        // exactly as a lexical escape is. Containment, not a link ban: a link
        // that stays under the tests root is still registered.
        dropped = `"${spec.ref.path}" resolves through a symbolic link to a file outside the tests root`;
      } else {
        // Delegated decision 2026-09-26 (review L4): one FILE registered under
        // two ids — the same path twice, `./x` vs `x`, a link to a sibling, or
        // `A.unit.ts` vs `a.unit.ts` (one file on APFS/NTFS) — made one spec
        // count as two, each with its own target list. Keyed on the real path
        // and on the lexical path, both case-folded, so the answer does not
        // depend on the filesystem it runs on: two paths that differ only in
        // case are refused even where they are two files, because the same
        // repo checked out on macOS makes them one. First wins, as with ids;
        // the later entry is dropped with a warning (sets `incomplete`).
        fileKeys = [foldPath(realFile), foldPath(file)];
        const owner = fileKeys
          .map((key) => byFile.get(key))
          .find((taken) => taken !== undefined);
        if (owner !== undefined) {
          dropped = `"${spec.ref.path}" is the same file (by real path or case-insensitive path) as the one already registered by entry \`${owner}\`; the first registration was kept`;
        }
      }
    } catch (error) {
      dropped =
        errnoOf(error) === "ENOENT"
          ? // `SpecInventory` explains the drop: an entry with no file is rot
            // rather than intent, because a spec that cannot run can never
            // confirm anything.
            `there is no file at "${spec.ref.path}"`
          : // Deliberately worded as unreadable rather than missing. The two
            // are not the same fact, and a note that conflates them sends
            // someone to write a spec that is already there.
            `the file at "${spec.ref.path}" could not be read: ${describeError(error)}`;
    }
    if (dropped !== undefined) {
      notes.push(
        note("warning", `dropped entry \`${spec.ref.id}\`: ${dropped}`),
      );
      continue;
    }

    byId.set(spec.ref.id, spec);
    for (const key of fileKeys) byFile.set(key, spec.ref.id);
    specs.push(spec);
  }

  if (declaredSpecs.length === 0) {
    // Distinguishable in a log from the absent-manifest case above and from a
    // manifest whose every entry was dropped — three different empty lists,
    // three different things to do about them.
    notes.push(
      note(
        "info",
        `${manifestPath} registers no specs; the registry was read in full and is empty`,
      ),
    );
  }

  // ── 4. what the manifest does not mention ───────────────────────────────
  const scan = await scanSpecFiles(root);
  const unregistered = scan.files
    .filter((file) => !claimed.has(file))
    .map((file) => relativeName(root, file))
    .sort(compare);

  if (unregistered.length > 0) {
    // Listed, never joined. A file matched by suffix has no declared targets,
    // and QA-16 forbids reading them out of the path — so the honest report is
    // "the repo may intend more than this inventory says", and the names of
    // the files a person has to look at to find out.
    notes.push(
      note(
        "warning",
        `${unregistered.length} spec-looking file(s) under the tests root are not registered in ${SPEC_MANIFEST_FILENAME}, so the repo may intend more than this inventory reports; their targets are NOT inferred from the path (QA-16): ${renderList(unregistered, UNREGISTERED_LIST_CAP)}`,
      ),
    );
  }
  if (scan.unreadable.length > 0) {
    // The count is repeated inside this note rather than referred to as "the
    // count above": when it is zero the warning above is not emitted at all,
    // and a floor that names nothing to be a floor of reads as a complete
    // answer to anyone who only sees this line.
    notes.push(
      note(
        "warning",
        `${scan.unreadable.length} director(y|ies) under the tests root could not be listed, so no file beneath them was examined and the unregistered spec-looking file count (${unregistered.length}) is a floor rather than a complete answer: ${renderList([...scan.unreadable].sort(compare), UNREGISTERED_LIST_CAP)}`,
      ),
    );
  }

  if (scan.proposed.length > 0) {
    notes.push(
      note(
        "info",
        `${scan.proposed.length} generated spec file(s) sit under ${PROPOSED_SPECS_DIRNAME}/ awaiting review; they are the output of \`tess generate\`, are armed by no live manifest, and are neither part of this inventory nor counted against its completeness: ${renderList([...scan.proposed].map((file) => relativeName(root, file)).sort(compare), UNREGISTERED_LIST_CAP)}`,
      ),
    );
  }
  if (scan.proposedUnreadable.length > 0) {
    notes.push(
      note(
        "info",
        `${scan.proposedUnreadable.length} director(y|ies) under ${PROPOSED_SPECS_DIRNAME}/ could not be listed, so the count of generated specs awaiting review is a floor; this does not affect the live inventory: ${renderList([...scan.proposedUnreadable].sort(compare), UNREGISTERED_LIST_CAP)}`,
      ),
    );
  }

  // ── 5. the answer ───────────────────────────────────────────────────────
  specs.sort((left, right) => compare(left.ref.id, right.ref.id));
  return inventory(specs, notes);
}
